// Reads content/projects/*.md and writes src/app/projects.generated.ts.
//
// Why a generated file instead of reading the .md files directly at
// import time: every consumer of `Projects` in src/app is a 'use client'
// component, so that module ends up in the browser bundle — it can't use
// `fs` there. This script does the file/frontmatter reading in Node
// ahead of time and emits a plain data file that's safe to bundle.
//
// Runs once before `dev`/`build` (see package.json). Pass --watch to keep
// running and regenerate on every change under content/projects/ — `npm
// run dev` does this for you so editing a .md file live-updates the site.

import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const CONTENT_DIR = path.join(process.cwd(), "content/projects");
const OUT_FILE = path.join(process.cwd(), "src/app/projects.generated.ts");

function extractSection(body: string, heading: string): string {
  // Match the heading on its own line (not just its leading text) so an
  // empty section doesn't greedily swallow the next "## ..." heading.
  const headingRe = new RegExp(`^##\\s*${heading}\\s*$`, "im");
  const match = headingRe.exec(body);
  if (!match) return "";

  const rest = body.slice(match.index + match[0].length);
  const nextHeading = /^##\s/m.exec(rest);
  return (nextHeading ? rest.slice(0, nextHeading.index) : rest).trim();
}

function slugFromFilename(filename: string): string {
  // Strip the ".md" extension and an optional leading "01-" ordering prefix.
  return filename.replace(/\.md$/, "").replace(/^\d+-/, "");
}

function generate(): void {
  const files = fs
    .readdirSync(CONTENT_DIR)
    .filter((f) => f.endsWith(".md"))
    .sort(); // ordering prefixes (01-, 02-, ...) control display order

  const projects = files.map((file) => {
    const raw = fs.readFileSync(path.join(CONTENT_DIR, file), "utf8");
    const { data, content } = matter(raw);

    return {
      slug: slugFromFilename(file),
      artistName: data.artistName ?? "",
      artistLink: data.artistLink ?? "",
      artistDescription: extractSection(content, "Artist Description"),
      workName: data.workName ?? "",
      workDescription: extractSection(content, "Work Description"),
      img: data.img ?? "",
      venue: data.venue ?? "",
      address: data.address ?? "",
      locationGoogleMapsLink: data.locationGoogleMapsLink ?? "",
      launchDate: String(data.launchDate ?? ""),
      coordinates: {
        lat: data.coordinates?.lat ?? 0,
        long: data.coordinates?.long ?? 0,
      },
    };
  });

  const output = `// AUTO-GENERATED by scripts/generate-projects.ts — do not edit by hand.
// Edit the source files in content/projects/*.md instead, then re-run
// \`npm run generate:projects\` (or just \`npm run dev\` / \`npm run build\`,
// which do it for you).

export interface RawProject {
  slug: string;
  artistName: string;
  artistLink: string;
  artistDescription: string;
  workName: string;
  workDescription: string;
  img: string;
  venue: string;
  address: string;
  locationGoogleMapsLink: string;
  launchDate: string;
  coordinates: { lat: number; long: number };
}

export const rawProjects: RawProject[] = ${JSON.stringify(projects, null, 2)};
`;

  fs.writeFileSync(OUT_FILE, output);
  console.log(
    `generate-projects: wrote ${projects.length} project(s) from content/projects/ -> ${path.relative(
      process.cwd(),
      OUT_FILE
    )}`
  );
}

generate();

if (process.argv.includes("--watch")) {
  console.log(`generate-projects: watching ${path.relative(process.cwd(), CONTENT_DIR)} for changes...`);
  let pending: NodeJS.Timeout | null = null;
  fs.watch(CONTENT_DIR, { recursive: true }, (_event, filename) => {
    if (!filename || !filename.endsWith(".md")) return;
    // Debounce: editors often fire several fs events (write + rename) per save.
    if (pending) clearTimeout(pending);
    pending = setTimeout(() => {
      try {
        generate();
      } catch (err) {
        console.error("generate-projects: failed to regenerate:", err);
      }
    }, 100);
  });
}
